GuestBook/Controllers/TamuController.cs
using GuestBook.DAL;
using GuestBook.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace GuestBook.Controllers
{
    public class TamuController : Controller
    {
        // GET: Tamu
        public ActionResult Index()
        {
            using (TamuDAL service = new TamuDAL())
            {
                
                var model = service.GetData().ToList();
                if (TempData["Pesan"] != null)
                {
                    ViewBag.Pesan = TempData["Pesan"].ToString();
                }
                return View(model);
            }
        }
        public ActionResult Search(string txtSearch)
        {
            using (TamuDAL svCat = new TamuDAL())
            {
                var results = svCat.Search(txtSearch).ToList();
                return View("Index", results);
            }
        }

        public ActionResult IndexUser()
        {
            string username = Session["username"].ToString();
            using (TamuDAL service = new TamuDAL())
            {
                return View(service.GetDataByUsername(username).ToList());
            }
        }

        [Authorize]
        public ActionResult Create()
        {
            if (Session["username"] == null)
            {
                if (User.Identity.IsAuthenticated)
                {
                    Session["username"] = User.Identity.Name;
                }
                else
                {
                    Response.Redirect("~/Login.aspx");
                }
            }
            return View();
        }

        
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Tamu tamu)
        {
            
            using (TamuDAL service = new TamuDAL())
            {
                
                    service.Add(tamu); 
            }
            return RedirectToAction("Index");
        }

        [Authorize]
        public ActionResult Edit(int id)
        {
            using (TamuDAL services = new TamuDAL())
            {
                var result = services.GetDataById(id);
                return View(result);
            }
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
       
        public ActionResult Edit(Tamu tamu)
        {
            using (TamuDAL services = new TamuDAL())
            {
               
                    services.Edit(tamu);

            }
            return RedirectToAction("Index");
        }

        [Authorize]
        public ActionResult Delete(int id)
        {
            using (TamuDAL service = new TamuDAL())
            {
             
                    service.Delete(id);
                    
            }
            return RedirectToAction("Index");
        }
    }
}

GuestBook/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>NY - Nando ♥ Yuri</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <div style="padding-left:70px;padding-top:15px">
                    @*@Html.ActionLink("PHOENIX", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })*@
                    <a href='@Url.Action("Index","Tamu")'><img src="~/Content/Image/ny.png" height="43" width="100" /></a>
                </div>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    
                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer style="color:white">
            <p>&copy; @DateTime.Now.Year - Nando Yuri Forever</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>